name: Deploy to Droplet via SSH

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: SSH Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 167.172.224.246
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/CSE416_ProjectCode/recipeApp
            git pull origin main
            npm install
            npm run build
            pm2 restart server

